WILDS_TPOSE_LIST =[
    ['MhBone_013', 'Hip'], ['MhBone_001', 'Spine_0'], ['MhBone_002', 'Spine_1'],
        ['MhBone_002', 'Spine_2'], ['MhBone_003', 'Neck_0'], ['MhBone_003', 'Neck_0_HJ_00'],
        ['MhBone_004', 'Head'], ['MhBone_005', 'L_Shoulder'], ['MhBone_080', 'L_UpperArm'],
        ['MhBone_007', 'L_Forearm'], ['MhBone_008', 'L_Hand'], ['MhBone_008', 'L_Wep'],
        ['MhBone_031', 'L_Thumb1'], ['MhBone_032', 'L_Thumb2'], ['MhBone_033', 'L_Thumb3'],
        ['MhBone_031', 'L_Thumb_HJ_00'], ['MhBone_032', 'L_Thumb_HJ_01'], ['MhBone_033', 'L_Thumb_HJ_02'],
        ['MhBone_031', 'L_Thumb_HJ_03'], ['MhBone_034', 'L_IndexF1'], ['MhBone_035', 'L_IndexF2'],
        ['MhBone_036', 'L_IndexF3'], ['MhBone_034', 'L_IndexF_HJ_01'], ['MhBone_035', 'L_IndexF_HJ_02'],
        ['MhBone_036', 'L_IndexF_HJ_03'], ['MhBone_034', 'L_IndexF_HJ_00'], ['MhBone_034', 'L_IndexF_HJ_04'],
        ['MhBone_037', 'L_MiddleF1'], ['MhBone_038', 'L_MiddleF2'], ['MhBone_039', 'L_MiddleF3'],
        ['MhBone_037', 'L_MiddleF_HJ_01'], ['MhBone_038', 'L_MiddleF_HJ_02'], ['MhBone_039', 'L_MiddleF_HJ_03'],
        ['MhBone_037', 'L_MiddleF_HJ_00'], ['MhBone_037', 'L_MiddleF_HJ_04'], ['MhBone_040', 'L_Palm'],
        ['MhBone_041', 'L_RingF1'], ['MhBone_042', 'L_RingF2'], ['MhBone_043', 'L_RingF3'],
        ['MhBone_041', 'L_RingF_HJ_01'], ['MhBone_042', 'L_RingF_HJ_02'], ['MhBone_043', 'L_RingF_HJ_03'],
        ['MhBone_041', 'L_RingF_HJ_00'], ['MhBone_041', 'L_RingF_HJ_04'], ['MhBone_044', 'L_PinkyF1'],
        ['MhBone_045', 'L_PinkyF2'], ['MhBone_046', 'L_PinkyF3'], ['MhBone_044', 'L_PinkyF_HJ_01'],
        ['MhBone_045', 'L_PinkyF_HJ_02'], ['MhBone_046', 'L_PinkyF_HJ_03'], ['MhBone_044', 'L_PinkyF_HJ_00'],
        ['MhBone_044', 'L_PinkyF_HJ_04'], ['MhBone_008', 'L_HandRZ_HJ_00'], ['MhBone_008', 'L_Hand_HJ_01'],
        ['MhBone_008', 'L_Wep_Sub'], ['MhBone_008', 'L_Hand_HJ_00'], ['MhBone_081', 'L_ForearmTwist_HJ_02'],
        ['MhBone_007', 'L_ForearmRY_HJ_00'], ['MhBone_007', 'L_ForearmRY_HJ_01'], ['MhBone_081', 'L_ForearmTwist_HJ_01'],
        ['MhBone_007', 'L_ForearmTwist_HJ_00'], ['MhBone_007', 'L_Forearm_HJ_00'], ['MhBone_007', 'L_Elbow_HJ_00'],
        ['MhBone_080', 'L_UpperArmTwist_HJ_00'], ['MhBone_006', 'L_UpperArmTwist_HJ_01'], ['MhBone_006', 'L_Triceps_HJ_00'],
        ['MhBone_006', 'L_Biceps_HJ_00'], ['MhBone_006', 'L_Biceps_HJ_01'], ['MhBone_006', 'L_UpperArmTwist_HJ_02'],
        ['MhBone_007', 'L_ForearmDouble_HJ_00'], ['MhBone_080', 'L_UpperArm_HJ_00'], ['MhBone_080', 'L_Deltoid_HJ_00'],
        ['MhBone_080', 'L_Deltoid_HJ_01'], ['MhBone_080', 'L_Deltoid_HJ_02'], ['MhBone_080', 'L_UpperArmDouble_HJ_00'],
        ['MhBone_005', 'L_Shoulder_HJ_00'], ['MhBone_009', 'R_Shoulder'], ['MhBone_082', 'R_UpperArm'],
        ['MhBone_011', 'R_Forearm'], ['MhBone_012', 'R_Hand'], ['MhBone_012', 'R_Wep'],
        ['MhBone_048', 'R_Thumb1'], ['MhBone_049', 'R_Thumb2'], ['MhBone_050', 'R_Thumb3'],
        ['MhBone_048', 'R_Thumb_HJ_00'], ['MhBone_049', 'R_Thumb_HJ_01'], ['MhBone_050', 'R_Thumb_HJ_02'],
        ['MhBone_048', 'R_Thumb_HJ_03'], ['MhBone_051', 'R_IndexF1'], ['MhBone_052', 'R_IndexF2'],
        ['MhBone_053', 'R_IndexF3'], ['MhBone_051', 'R_IndexF_HJ_01'], ['MhBone_052', 'R_IndexF_HJ_02'],
        ['MhBone_053', 'R_IndexF_HJ_03'], ['MhBone_051', 'R_IndexF_HJ_00'], ['MhBone_051', 'R_IndexF_HJ_04'],
        ['MhBone_054', 'R_MiddleF1'], ['MhBone_055', 'R_MiddleF2'], ['MhBone_056', 'R_MiddleF3'],
        ['MhBone_054', 'R_MiddleF_HJ_01'], ['MhBone_055', 'R_MiddleF_HJ_02'], ['MhBone_056', 'R_MiddleF_HJ_03'],
        ['MhBone_054', 'R_MiddleF_HJ_00'], ['MhBone_054', 'R_MiddleF_HJ_04'], ['MhBone_057', 'R_Palm'],
        ['MhBone_058', 'R_RingF1'], ['MhBone_059', 'R_RingF2'], ['MhBone_060', 'R_RingF3'],
        ['MhBone_058', 'R_RingF_HJ_01'], ['MhBone_059', 'R_RingF_HJ_02'], ['MhBone_060', 'R_RingF_HJ_03'],
        ['MhBone_058', 'R_RingF_HJ_00'], ['MhBone_058', 'R_RingF_HJ_04'], ['MhBone_061', 'R_PinkyF1'],
        ['MhBone_062', 'R_PinkyF2'], ['MhBone_063', 'R_PinkyF3'], ['MhBone_061', 'R_PinkyF_HJ_01'],
        ['MhBone_062', 'R_PinkyF_HJ_02'], ['MhBone_063', 'R_PinkyF_HJ_03'], ['MhBone_061', 'R_PinkyF_HJ_00'],
        ['MhBone_061', 'R_PinkyF_HJ_04'], ['MhBone_012', 'R_HandRZ_HJ_00'], ['MhBone_012', 'R_Hand_HJ_01'],
        ['MhBone_012', 'R_Wep_Sub'], ['MhBone_012', 'R_Hand_HJ_00'], ['MhBone_083', 'R_ForearmTwist_HJ_02'],
        ['MhBone_011', 'R_ForearmRY_HJ_00'], ['MhBone_011', 'R_ForearmRY_HJ_01'], ['MhBone_083', 'R_ForearmTwist_HJ_01'],
        ['MhBone_011', 'R_ForearmTwist_HJ_00'], ['MhBone_011', 'R_Shield'], ['MhBone_011', 'R_Forearm_HJ_00'],
        ['MhBone_011', 'R_Elbow_HJ_00'], ['MhBone_082', 'R_UpperArmTwist_HJ_00'], ['MhBone_010', 'R_UpperArmTwist_HJ_01'],
        ['MhBone_010', 'R_Triceps_HJ_00'], ['MhBone_010', 'R_Biceps_HJ_00'], ['MhBone_010', 'R_Biceps_HJ_01'],
        ['MhBone_010', 'R_UpperArmTwist_HJ_02'], ['MhBone_011', 'R_ForearmDouble_HJ_00'], ['MhBone_082', 'R_UpperArm_HJ_00'],
        ['MhBone_082', 'R_Deltoid_HJ_00'], ['MhBone_082', 'R_Deltoid_HJ_01'], ['MhBone_082', 'R_Deltoid_HJ_02'],
        ['MhBone_082', 'R_UpperArmDouble_HJ_00'], ['MhBone_009', 'R_Shoulder_HJ_00'], ['MhBone_005', 'L_Traps_HJ_00'],
        ['MhBone_005', 'L_Traps_HJ_01'], ['MhBone_005', 'L_Pec_HJ_00'], ['MhBone_005', 'L_Pec_HJ_01'],
        ['MhBone_005', 'L_Lats_HJ_00'], ['MhBone_005', 'L_Lats_HJ_01'], ['MhBone_009', 'R_Traps_HJ_00'],
        ['MhBone_009', 'R_Traps_HJ_01'], ['MhBone_009', 'R_Pec_HJ_00'], ['MhBone_009', 'R_Pec_HJ_01'],
        ['MhBone_009', 'R_Lats_HJ_00'], ['MhBone_009', 'R_Lats_HJ_01'], ['MhBone_002', 'Spine_2_HJ_00'],
        ['MhBone_002', 'Spine_1_HJ_00'], ['MhBone_001', 'Spine_0_HJ_00'], ['MhBone_014', 'L_Thigh'],
        ['MhBone_015', 'L_Knee'], ['MhBone_015', 'L_Shin'], ['MhBone_016', 'L_Foot'],
        ['MhBone_017', 'L_Toe'], ['MhBone_016', 'L_Foot_HJ_00'], ['MhBone_015', 'L_Calf_HJ_00'],
        ['MhBone_015', 'L_Shin_HJ_00'], ['MhBone_015', 'L_Shin_HJ_01'], ['MhBone_015', 'L_Knee_HJ_00'],
        ['MhBone_015', 'L_KneeDouble_HJ_00'], ['MhBone_015', 'L_KneeRX_HJ_00'], ['MhBone_014', 'L_ThighTwist_HJ_00'],
        ['MhBone_014', 'L_ThighTwist_HJ_01'], ['MhBone_015', 'L_ThighTwist_HJ_02'], ['MhBone_018', 'R_Thigh'],
        ['MhBone_019', 'R_Knee'], ['MhBone_019', 'R_Shin'], ['MhBone_020', 'R_Foot'],
        ['MhBone_021', 'R_Toe'], ['MhBone_020', 'R_Foot_HJ_00'], ['MhBone_019', 'R_Calf_HJ_00'],
        ['MhBone_019', 'R_Shin_HJ_00'], ['MhBone_019', 'R_Shin_HJ_01'], ['MhBone_019', 'R_Knee_HJ_00'],
        ['MhBone_019', 'R_KneeDouble_HJ_00'], ['MhBone_019', 'R_KneeRX_HJ_00'], ['MhBone_018', 'R_ThighTwist_HJ_00'],
        ['MhBone_018', 'R_ThighTwist_HJ_01'], ['MhBone_019', 'R_ThighTwist_HJ_02'], ['MhBone_014', 'L_ThighRZ_HJ_00'],
        ['MhBone_014', 'L_ThighRZ_HJ_01'], ['MhBone_018', 'R_ThighRZ_HJ_00'], ['MhBone_018', 'R_ThighRZ_HJ_01'],
        ['MhBone_014', 'L_Hip_HJ_00'], ['MhBone_014', 'L_Hip_HJ_01'], ['MhBone_018', 'R_Hip_HJ_00'],
        ['MhBone_018', 'R_Hip_HJ_01'], ['MhBone_014', 'L_ThighRX_HJ_00'], ['MhBone_014', 'L_ThighRX_HJ_01'],
        ['MhBone_018', 'R_ThighRX_HJ_00'], ['MhBone_018', 'R_ThighRX_HJ_01'], ['MhBone_013', 'Hip_HJ_00'],
]

ENDFIELD_SNAP_MAP = [
        ['Pelvis', 'Hip'],
    ['Spine', 'Spine_0'],
    ['Spine1', 'Spine_1'],
    ['Spine2', 'Spine_2'],
    ['Neck', 'Neck_0'],
    ['Neck', 'Neck_0_HJ_00'],
    ['Head', 'Head'],
    ['L_Clavicle', 'L_Shoulder'],
    ['L_UpperArm', 'L_UpperArm'],
    ['L_Forearm', 'L_Forearm'],
    ['L_Hand', 'L_Hand'],
    ['L_Hand_ty_plus', 'L_Wep'],
    ['L_Finger0', 'L_Thumb1'],
    ['L_Finger01', 'L_Thumb2'],
    ['L_Finger02', 'L_Thumb3'],
    ['L_Finger0', 'L_Thumb_HJ_00'],
    ['L_Finger01', 'L_Thumb_HJ_01'],
    ['L_Finger02', 'L_Thumb_HJ_02'],
    ['L_Finger0', 'L_Thumb_HJ_03'],
    ['L_Finger1', 'L_IndexF1'],
    ['L_Finger11', 'L_IndexF2'],
    ['L_Finger12', 'L_IndexF3'],
    ['L_Finger1', 'L_IndexF_HJ_01'],
    ['L_Finger11', 'L_IndexF_HJ_02'],
    ['L_Finger12', 'L_IndexF_HJ_03'],
    ['L_Finger1', 'L_IndexF_HJ_00'],
    ['L_Finger1', 'L_IndexF_HJ_04'],
    ['L_Finger2', 'L_MiddleF1'],
    ['L_Finger21', 'L_MiddleF2'],
    ['L_Finger22', 'L_MiddleF3'],
    ['L_Finger2', 'L_MiddleF_HJ_01'],
    ['L_Finger21', 'L_MiddleF_HJ_02'],
    ['L_Finger21', 'L_MiddleF_HJ_03'],
    ['L_Finger2', 'L_MiddleF_HJ_00'],
    ['L_Finger2', 'L_MiddleF_HJ_04'],
    ['L_Hand', 'L_Palm'],
    ['L_Finger3', 'L_RingF1'],
    ['L_Finger31', 'L_RingF2'],
    ['L_Finger32', 'L_RingF3'],
    ['L_Finger3', 'L_RingF_HJ_01'],
    ['L_Finger31', 'L_RingF_HJ_02'],
    ['L_Finger32', 'L_RingF_HJ_03'],
    ['L_Finger3', 'L_RingF_HJ_00'],
    ['L_Finger3', 'L_RingF_HJ_04'],
    ['L_Finger4', 'L_PinkyF1'],
    ['L_Finger41', 'L_PinkyF2'],
    ['L_Finger42', 'L_PinkyF3'],
    ['L_Finger4', 'L_PinkyF_HJ_01'],
    ['L_Finger41', 'L_PinkyF_HJ_02'],
    ['L_Finger42', 'L_PinkyF_HJ_03'],
    ['L_Finger4', 'L_PinkyF_HJ_00'],
    ['L_Finger4', 'L_PinkyF_HJ_04'],
    ['L_Hand_ty_minus', 'L_HandRZ_HJ_00'],
    ['L_Hand', 'L_Hand_HJ_01'],
    ['L_Hand_ty_plus', 'L_Wep_Sub'],
    ['L_Hand', 'L_Hand_HJ_00'],
    ['L_ForeTwist1', 'L_ForearmTwist_HJ_02'],
    ['L_Forearm', 'L_ForearmRY_HJ_00'],
    ['L_Forearm', 'L_ForearmRY_HJ_01'],
    ['L_ForeTwist1', 'L_ForearmTwist_HJ_01'],
    ['L_ForeTwist', 'L_ForearmTwist_HJ_00'],
    ['L_Forearm', 'L_Forearm_HJ_00'],
    ['L_Forearm', 'L_Elbow_HJ_00'],
    ['L_UpperArm', 'L_UpperArmTwist_HJ_00'],
    ['LUpArmTwist', 'L_UpperArmTwist_HJ_01'],
    ['LUpArmTwist', 'L_Triceps_HJ_00'],
    ['LUpArmTwist', 'L_Biceps_HJ_00'],
    ['LUpArmTwist', 'L_Biceps_HJ_01'],
    ['LUpArmTwist1', 'L_UpperArmTwist_HJ_02'],
    ['L_Forearm', 'L_ForearmDouble_HJ_00'],
    ['L_UpperArm_tz_plus', 'L_UpperArm_HJ_00'],
    ['L_UpperArm', 'L_Deltoid_HJ_00'],
    ['L_UpperArm_tz_plus', 'L_Deltoid_HJ_01'],
    ['L_UpperArm_ty_plus', 'L_Deltoid_HJ_02'],
    ['L_UpperArm', 'L_UpperArmDouble_HJ_00'],
    ['L_Clavicle', 'L_Shoulder_HJ_00'],
    ['R_Clavicle', 'R_Shoulder'],
    ['R_UpperArm', 'R_UpperArm'],
    ['R_Forearm', 'R_Forearm'],
    ['R_Hand', 'R_Hand'],
    ['R_Hand_ty_plus', 'R_Wep'],
    ['R_Finger0', 'R_Thumb1'],
    ['R_Finger01', 'R_Thumb2'],
    ['R_Finger02', 'R_Thumb3'],
    ['R_Finger0', 'R_Thumb_HJ_00'],
    ['R_Finger01', 'R_Thumb_HJ_01'],
    ['R_Finger02', 'R_Thumb_HJ_02'],
    ['R_Finger0', 'R_Thumb_HJ_03'],
    ['R_Finger1', 'R_IndexF1'],
    ['R_Finger11', 'R_IndexF2'],
    ['R_Finger12', 'R_IndexF3'],
    ['R_Finger1', 'R_IndexF_HJ_01'],
    ['R_Finger11', 'R_IndexF_HJ_02'],
    ['R_Finger12', 'R_IndexF_HJ_03'],
    ['R_Finger1', 'R_IndexF_HJ_00'],
    ['R_Finger1', 'R_IndexF_HJ_04'],
    ['R_Finger2', 'R_MiddleF1'],
    ['R_Finger21', 'R_MiddleF2'],
    ['R_Finger22', 'R_MiddleF3'],
    ['R_Finger2', 'R_MiddleF_HJ_01'],
    ['R_Finger21', 'R_MiddleF_HJ_02'],
    ['R_Finger22', 'R_MiddleF_HJ_03'],
    ['R_Finger2', 'R_MiddleF_HJ_00'],
    ['R_Finger2', 'R_MiddleF_HJ_04'],
    ['R_Hand', 'R_Palm'],
    ['R_Finger3', 'R_RingF1'],
    ['R_Finger31', 'R_RingF2'],
    ['R_Finger32', 'R_RingF3'],
    ['R_Finger3', 'R_RingF_HJ_01'],
    ['R_Finger31', 'R_RingF_HJ_02'],
    ['R_Finger32', 'R_RingF_HJ_03'],
    ['R_Finger3', 'R_RingF_HJ_00'],
    ['R_Finger3', 'R_RingF_HJ_04'],
    ['R_Finger4', 'R_PinkyF1'],
    ['R_Finger41', 'R_PinkyF2'],
    ['R_Finger42', 'R_PinkyF3'],
    ['R_Finger4', 'R_PinkyF_HJ_01'],
    ['R_Finger41', 'R_PinkyF_HJ_02'],
    ['R_Finger42', 'R_PinkyF_HJ_03'],
    ['R_Finger4', 'R_PinkyF_HJ_00'],
    ['R_Finger4', 'R_PinkyF_HJ_04'],
    ['R_Hand_ty_minus', 'R_HandRZ_HJ_00'],
    ['R_Hand', 'R_Hand_HJ_01'],
    ['R_Hand_ty_plus', 'R_Wep_Sub'],
    ['R_Hand', 'R_Hand_HJ_00'],
    ['R_ForeTwist1', 'R_ForearmTwist_HJ_02'],
    ['R_Forearm', 'R_ForearmRY_HJ_00'],
    ['R_Forearm', 'R_ForearmRY_HJ_01'],
    ['R_ForeTwist1', 'R_ForearmTwist_HJ_01'],
    ['R_ForeTwist', 'R_ForearmTwist_HJ_00'],
    ['R_Forearm', 'R_Shield'],
    ['R_Forearm', 'R_Forearm_HJ_00'],
    ['R_Forearm', 'R_Elbow_HJ_00'],
    ['R_UpperArm', 'R_UpperArmTwist_HJ_00'],
    ['RUpArmTwist', 'R_UpperArmTwist_HJ_01'],
    ['RUpArmTwist', 'R_Triceps_HJ_00'],
    ['RUpArmTwist', 'R_Biceps_HJ_00'],
    ['RUpArmTwist', 'R_Biceps_HJ_01'],
    ['RUpArmTwist1', 'R_UpperArmTwist_HJ_02'],
    ['R_Forearm', 'R_ForearmDouble_HJ_00'],
    ['R_UpperArm_tz_plus', 'R_UpperArm_HJ_00'],
    ['R_UpperArm', 'R_Deltoid_HJ_00'],
    ['R_UpperArm_tz_plus', 'R_Deltoid_HJ_01'],
    ['R_UpperArm_ty_plus', 'R_Deltoid_HJ_02'],
    ['R_UpperArm', 'R_UpperArmDouble_HJ_00'],
    ['R_Clavicle', 'R_Shoulder_HJ_00'],
    ['L_Clavicle', 'L_Traps_HJ_00'],
    ['L_Clavicle', 'L_Traps_HJ_01'],
    ['L_UpperArm_ty_minus', 'L_Pec_HJ_00'],
    ['L_UpperArm_ty_minus', 'L_Pec_HJ_01'],
    ['L_Clavicle', 'L_Lats_HJ_00'],
    ['L_Clavicle', 'L_Lats_HJ_01'],
    ['R_Clavicle', 'R_Traps_HJ_00'],
    ['R_Clavicle', 'R_Traps_HJ_01'],
    ['R_UpperArm_ty_minus', 'R_Pec_HJ_00'],
    ['R_UpperArm_ty_minus', 'R_Pec_HJ_01'],
    ['R_Clavicle', 'R_Lats_HJ_00'],
    ['R_Clavicle', 'R_Lats_HJ_01'],
    ['Spine2', 'Spine_2_HJ_00'],
    ['Spine1', 'Spine_1_HJ_00'],
    ['Spine0', 'Spine_0_HJ_00'],
    ['L_Thigh', 'L_Thigh'],
    ['L_Calf', 'L_Knee'],
    ['L_Calf', 'L_Shin'],
    ['L_Foot', 'L_Foot'],
    ['L_Toe0', 'L_Toe'],
    ['L_Foot_ty_minus', 'L_Foot_HJ_00'],
    ['L_Calf', 'L_Calf_HJ_00'],
    ['LCalfTwist', 'L_Shin_HJ_00'],
    ['LCalfTwist1', 'L_Shin_HJ_01'],
    ['L_Calf_ty_plus', 'L_Knee_HJ_00'],
    ['L_Calf_ty_plus', 'L_KneeDouble_HJ_00'],
    ['L_Calf_ty_minus', 'L_KneeRX_HJ_00'],
    ['L_Thigh', 'L_ThighTwist_HJ_00'],
    ['LThighTwist', 'L_ThighTwist_HJ_01'],
    ['LThighTwist1', 'L_ThighTwist_HJ_02'],
    ['R_Thigh', 'R_Thigh'],
    ['R_Calf', 'R_Knee'],
    ['R_Calf', 'R_Shin'],
    ['R_Foot', 'R_Foot'],
    ['R_Toe0', 'R_Toe'],
    ['R_Foot_ty_minus', 'R_Foot_HJ_00'],
    ['R_Calf', 'R_Calf_HJ_00'],
    ['RCalfTwist', 'R_Shin_HJ_00'],
    ['RCalfTwist1', 'R_Shin_HJ_01'],
    ['R_Calf_ty_plus', 'R_Knee_HJ_00'],
    ['R_Calf_ty_plus', 'R_KneeDouble_HJ_00'],
    ['R_Calf_ty_minus', 'R_KneeRX_HJ_00'],
    ['R_Thigh', 'R_ThighTwist_HJ_00'],
    ['RThighTwist', 'R_ThighTwist_HJ_01'],
    ['RThighTwist1', 'R_ThighTwist_HJ_02'],
    ['L_Thigh', 'L_ThighRZ_HJ_00'],
    ['L_Thigh_tz_minus', 'L_ThighRZ_HJ_01'],
    ['R_Thigh', 'R_ThighRZ_HJ_00'],
    ['R_Thigh_tz_minus', 'R_ThighRZ_HJ_01'],
    ['L_Thigh', 'L_Hip_HJ_00'],
    ['L_Thigh_ty_minus', 'L_Hip_HJ_01'],
    ['R_Thigh', 'R_Hip_HJ_00'],
    ['R_Thigh_ty_minus', 'R_Hip_HJ_01'],
    ['L_Thigh', 'L_ThighRX_HJ_00'],
    ['L_Thigh_ty_plus', 'L_ThighRX_HJ_01'],
    ['R_Thigh', 'R_ThighRX_HJ_00'],
    ['R_Thigh_ty_plus', 'R_ThighRX_HJ_01'],
    ['Pelvis', 'Hip_HJ_00'],

    ("face_Head", "HeadAll_SCL"),
    ("browLf01Joint", "L_EyeBrow_A_LOD01"),
    ("browLf02Joint", "L_EyeBrow_B_LOD01"),
    ("browLf03Joint", "L_EyeBrow_B_LOD01"),
    ("browLf04Joint", "L_EyeBrow_B_LOD01"),
    ("browLf05Joint", "L_EyeBrow_C_LOD01"),
    ("browLineLfUp01Joint", "L_EyeBrow_A_LOD01"),
    ("browLineLfUp02Joint", "L_EyeBrow_B_LOD01"),
    ("browLineLfUp03Joint", "L_EyeBrow_C_LOD01"),
    ("browLineLf01Joint", "L_DoubleEyeLid_A_LOD00"),
    ("browLineLf02Joint", "L_DoubleEyeLid_LOD01"),
    ("browLineLf03Joint", "L_DoubleEyeLid_B_LOD00"),
    ("browRt01Joint", "R_EyeBrow_A_LOD01"),
    ("browRt02Joint", "R_EyeBrow_B_LOD01"),
    ("browRt03Joint", "R_EyeBrow_B_LOD01"),
    ("browRt04Joint", "R_EyeBrow_B_LOD01"),
    ("browRt05Joint", "R_EyeBrow_C_LOD01"),
    ("browLineRtUp01Joint", "R_EyeBrow_A_LOD01"),
    ("browLineRtUp02Joint", "R_EyeBrow_B_LOD01"),
    ("browLineRtUp03Joint", "R_EyeBrow_C_LOD01"),
    ("browLineRt01Joint", "R_DoubleEyeLid_A_LOD00"),
    ("browLineRt02Joint", "R_DoubleEyeLid_LOD01"),
    ("browLineRt03Joint", "R_DoubleEyeLid_B_LOD00"),
    ("faceLfIrisJoint", "L_EyeJ_LOD02"),
    ("faceLfHighlightJoint", "L_EyeJ_LOD02"),
    ("faceLfHighlightJointA", "L_EyeJ_LOD02"),
    ("faceLfHighlightJointB", "L_EyeJ_LOD02"),
    ("faceLfPupilJoint", "L_EyeJ_LOD02"),
    ("eyeLf01Joint", "L_InnerEyeJ_LOD02"),
    ("eyeLf01EyelashJoint", "L_UpEyeLid_A_LOD00"),
    ("eyeLf02Joint", "L_UpEyeLid_A_LOD00"),
    ("eyeLf02EyelashJoint", "L_UpEyeLid_A_LOD00"),
    ("eyeLf03Joint", "L_UpEyeLid_LOD01"),
    ("eyeLf03EyelashJoint", "L_UpEyeLid_LOD01"),
    ("eyeLf03IrissdJoint", "L_UpEyeLid_LOD01"),
    ("eyeLf04Joint", "L_UpEyeLid_B_LOD00"),
    ("eyeLf04EyelashJoint", "L_UpEyeLid_B_LOD00"),
    ("eyeLf05Joint", "L_OuterEyeJ_LOD02"),
    ("eyeLf05EyelashJoint", "L_UpEyeLid_B_LOD00"),
    ("eyeLf06Joint", "L_LoEyeLid_B_LOD00"),
    ("eyeLf07Joint", "L_LoEyeLid_LOD01"),
    ("eyeLf08Joint", "L_LoEyeLid_A_LOD00"),
    ("faceRtIrisJoint", "R_EyeJ_LOD02"),
    ("faceRtHighlightJoint", "R_EyeJ_LOD02"),
    ("faceRtHighlightJointA", "R_EyeJ_LOD02"),
    ("faceRtHighlightJointB", "R_EyeJ_LOD02"),
    ("faceRtPupilJoint", "R_EyeJ_LOD02"),
    ("eyeRt01Joint", "R_InnerEyeJ_LOD02"),
    ("eyeRt01EyelashJoint", "R_UpEyeLid_A_LOD00"),
    ("eyeRt02Joint", "R_UpEyeLid_A_LOD00"),
    ("eyeRt02EyelashJoint", "R_UpEyeLid_A_LOD00"),
    ("eyeRt03Joint", "R_UpEyeLid_LOD01"),
    ("eyeRt03EyelashJoint", "R_UpEyeLid_LOD01"),
    ("eyeRt03IrissdJoint", "R_UpEyeLid_LOD01"),
    ("eyeRt04Joint", "R_UpEyeLid_B_LOD00"),
    ("eyeRt04EyelashJoint", "R_UpEyeLid_B_LOD00"),
    ("eyeRt05Joint", "R_OuterEyeJ_LOD02"),
    ("eyeRt05EyelashJoint", "R_UpEyeLid_B_LOD00"),
    ("eyeRt06Joint", "R_LoEyeLid_B_LOD00"),
    ("eyeRt07Joint", "R_LoEyeLid_LOD01"),
    ("eyeRt08Joint", "R_LoEyeLid_A_LOD00"),
    ("NoseMd01Joint", "C_Nose_LOD01"),
    ("lineJoint", "HeadAll_SCL"),
    ("faceMdToothUpJoint", "UpperTeeth"),
    ("line_toothJoint", "UpperTeeth"),
    ("faceMdToothDnJoint", "LowerTeeth"),
    ("TongueMd04Joint", "C_TongueC_LOD01"),
    ("TongueMd03Joint", "C_TongueB_LOD01"),
    ("TongueMd02Joint", "C_TongueB_LOD01"),
    ("TongueMd01Joint", "C_TongueA_LOD01"),
    ("lipLdn1Joint", "L_cornerLip_B_LOD01"),
    ("lipLdn2Joint", "L_loLip_BT_LOD00"),
    ("lipLdn3Joint", "L_loLip_T_LOD01"),
    ("lipLdn4Joint", "L_loLip_AT_LOD00"),
    ("lipMdnJoint", "C_loLip_T_LOD01"),
    ("lipRdn1Joint", "R_cornerLip_B_LOD01"),
    ("lipRdn2Joint", "R_loLip_BT_LOD00"),
    ("lipRdn3Joint", "R_loLip_T_LOD01"),
    ("lipRdn4Joint", "R_loLip_AT_LOD00"),
    ("lipLup1Joint", "R_cornerLip_B_LOD01"),
    ("lipLup2Joint", "L_upLip_BT_LOD00"),
    ("lipLup3Joint", "L_upLip_T_LOD01"),
    ("lipLup4Joint", "L_upLip_AT_LOD00"),
    ("lipMupJoint", "C_upLip_T_LOD01"),
    ("lipRup1Joint", "R_cornerLip_B_LOD01"),
    ("lipRup2Joint", "R_upLip_BT_LOD00"),
    ("lipRup3Joint", "R_upLip_T_LOD01"),
    ("lipRup4Joint", "R_upLip_AT_LOD00"),
    ("faceMdJawDnJoint", "C_Chin_LOD01"),
    ("faceLfCheekOtDnJoint", "L_JawLine_LOD01"),
    ("faceLfCheekOtInJoint", "L_malarFat_B_LOD01"),
    ("faceLfCheekOtJoint", "L_Cheek_LOD02"),
    ("faceLfCheekOtUpJoint", "L_CheekBone_LOD02"),
    ("faceRtCheekOtDnJoint", "R_JawLine_LOD01"),
    ("faceRtCheekOtInJoint", "R_malarFat_B_LOD01"),
    ("faceRtCheekOtJoint", "R_Cheek_LOD02"),
    ("faceRtCheekOtUpJoint", "R_CheekBone_LOD02"),
]